[project]
name = "hazeater"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "metatrader5>=5.0.5430",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.6",
]

[tool.uv]
package = true
